### ISSUE TITLE
Problem when importing ConfigSpace (0.4.17)

### ISSUE THREAD

**Issue by drake666** [automl/ConfigSpace#173]
Today, when I've tried importing the ConfigSpace package on Ubuntun 18.04, with python 3.8.0, the action raised a ValueError:

```
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ConfigSpace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxime/pipe-inspection/machine_learning/training/.venv/lib/python3.8/site-packages/ConfigSpace/__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.pyx", line 39, in init ConfigSpace.configuration_space
  File "ConfigSpace/hyperparameters.pyx", line 1, in init ConfigSpace.hyperparameters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

```

I'm currently using numpy 1.19.5 (can't use 1.20.0 since I'm also using tensorflow 2.4.0). Am I alone with this predicament?

**Comment by jbedorf** [comment]
I ran into the same issue. The issue is caused by the release of numpy 1.20.0 a few days ago. The installation of ConfigSpace does not restrict which numpy version that is used during build process, and as such the latest version is downloaded during the compilation of the ConfigSpace package. Which means that ConfigSpace is compiled against numpy 1.20.0 which has a different PyObject size than the pre 1.20 versions, and the one installed in your environment for usage.

I've found two ways to work around it for now:

1. Disable pip's build isolation 

Run pip install with the 'no-build-isolation' flag. This way pip will use your already installed numpy version: "pip install --no-build-isolation ConfigSpace==0.4.16"

`pip install --no-build-isolation ConfigSpace==0.4.16`

2. Edit the package source

Clone the repository, and modify, the [pyproject.toml](https://github.com/automl/ConfigSpace/blob/master/pyproject.toml) file to read:  

```
[build-system]
requires = ["setuptools", "wheel", "numpy < 1.20.0", "Cython"]
```
Then create/install the package. (python setup.py sdist ; pip install dist/...)

**Comment by benjamc** [comment]
Same problem here. 

Found a solution:
First, uninstall ConfigSpace
`pip uninstall ConfigSpace`
Then do following steps:
Clone repo:
`git clone https://github.com/automl/ConfigSpace.git`
`cd ConfigSpace`
Build binaries:
`python setup.py bdist`
Install package from local folder:
`pip install ~/Documents/repos/ConfigSpace/`

I am using ubuntu 20.04, anaconda, python 3.8 and numpy 1.19.2.

**Comment by drake666** [comment]
Thanks a lot! 
I've tried to solve that problem for an embarrassing length of time yesterday and I'm really happy someone found a solution.

**Comment by mfeurer** [comment]
Thanks @jbedorf for explaining the issue and to @jbedorf and @benjamc for posting solutions! Do you know of a way that we as maintainers can circumvent this issue?

**Comment by jbedorf** [comment]
I was wondering the same so did some more research. There is this package that has been specifically created for the issue seen here: https://github.com/scipy/oldest-supported-numpy 

Changing the build-system to look like this solves it, at least for my use-case.
```
[build-system]
requires = ["setuptools", "wheel", "Cython", "oldest-supported-numpy"]
```

**Comment by mfeurer** [comment]
Ah, did not know this. In case anyone wants to open a PR to contribute this change I'd be very happy about this.

**Comment by stradigi-mario-bruno** [comment]
@mfeurer I opened one https://github.com/automl/ConfigSpace/pull/175

**Comment by gradientsky** [comment]
You have to install same version of `numpy` and `cython` you have in tour setup config BEFORE `ConfigSpace` is installed. I had the same problem and I had both numpy and cython of specific version in my requirements, but ConfigSpace was installing before it and was using numpy from Conda (1.20.x), while I needed 1.19.5.

**Comment by leezu** [comment]
I think the problem here is that ConfigSpace has opted in to use pip build isolation feature, even though it relies on compiling native numpy code. I recommend you do not opt in to build isolation but rather use the "legacy" build https://github.com/facebookresearch/fairscale/commit/e92e85ceb5bb1352e2b4a0f645275f181a159018

**Comment by mfeurer** [comment]
> I think the problem here is that ConfigSpace has opted in to use pip build isolation feature, even though it relies on compiling native numpy code which can obviously cause ABI issues.

Thanks a lot for your input. I'm not an expert in python installation stuff so I for now went with the solution from @stradigi-mario-bruno as this is also used by scikit-learn (which I usually try to use as a reference and which probably is pretty similar in that it uses both python and cython together with numpy). The reason I used build isolation is because pip was advocating for supporting the specific PE and not mentioning any specific downsides. Therefore I'm wondering whether the fix you posted is future-proof and how many people would actually run into the edge case you mentioned or whether the fix from @stradigi-mario-bruno together with a potential wheel would be the more future-proof and easier to maintain?

**Comment by leezu** [comment]
The fix by @stradigi-mario-bruno assumes numpy has a stable ABI across all possible numpy versions that could be available at runtime. Only the numpy devs can answer this question, but maybe it's true for numpy. In general it's not true, especially if C++ is involved as C++ code does not have a stable ABI and the general fix is thus to disable pip build isolation.

**Comment by gradientsky** [comment]
Could you please advise on a timeline when the next release with #175 will be available?

**Comment by mfeurer** [comment]
It should now be available on pypi.

**Comment by mfeurer** [comment]
I just stumbled upon a page on this in the numpy docs, posting it here in case we need this in the future: https://numpy.org/devdocs/user/depending_on_numpy.html
