### ISSUE TITLE
`default_value` not part of the hash

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#238]
Similar to #232 we do not consider the default value for the hash, which should be fixed.

**Comment by eddiebergman** [comment]
Not sure what exactly it was refering too but now the hyperparameters are dataclasses which just hashes all attributes. `__eq__` still ignores ordering of categorical values but `__hash__` will not. `__hash__` is usually used for object identification and sets/mappings. I'm not sure we necessarily want the `__hash__` to consider the choices as unordered, since they are different objects that happen to be equivalent.

**Comment by eddiebergman** [comment]
Closing as `__hash__` was removed, however if someone has a good reason for `__hash__` to exist, we can revisit this.
