### ISSUE TITLE
Create TruncatedNormalHyperparameter

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#302]
To decouple the code for bounded and unbounded normal hyperparameters.

**Comment by eddiebergman** [comment]
@Neonkraft

The initial reaction was to have a heirarchy of `NormalFloatHyperparameter -> TruncatedNormalHyperparameter` but then checking for a non-truncated `Normal` becomes tedious.

```
x = NormalFloatHyperparameter(...)
y = TruncatedNormalFloatHyperparameter(...)

items = [x, y, ...]  # Some other hyperparameter types
for item in items:
    if isinstance(item, NormalFloatHyperparameter):
        ... # This would match both x and y
```

The correct solution would then be:
```python
if isinstance(item, NormalFloatHyperparameter) and not isinstance(item, TruncatedNormalFloatHyperparameter):
    ... # This is the only way to match just x
```

I'm okay with some minor code duplication to keep these seperated, otherwise we need some `_private` superclass, which just makes the heirarchy of hyperparameters more complex.

---

This would also constitute a pretty major breaking change and a version bump. This should probably be done at the same time as doing so for `Uniform` and possible `Beta` params
