### ISSUE TITLE
Check that a condition is only part of one ConfigurationSpace object

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#72]
by generating a random number for the configuration space on instantiation. When a condition is added, the configuration space will save it in the condition object, and error if there already is a different random number. Thereby, the bug of having a condition in two configuration spaces is effectively prevented.

**Comment by eddiebergman** [comment]
What's the issue of having them in two different spaces?

**Comment by eddiebergman** [comment]
This could also potentially be an issue if the hyperparameters are shared between two configuration spaces, but the hyperparameters have different vector indices.

Since the condition is the only thing shared, the information that it was added to a space needs to somehow live on that condition. Potential solutions:
* `set_vector_idx` also takes in some identifier, some combination of the spaces name and seeding. Not sure what issues this would cause though.
* Ignore it, consider it user error and document this

**Comment by eddiebergman** [comment]
I would consider this a user error honestly and make sure to document this clearly when dealing with conditionals, it's much simpler and defensive checking into non-usual behaviours is an endless battle for Python.

Feel free to re-open this if you feel otherwise @mfeurer
